services:
  api:
    image: 876497563387.dkr.ecr.ap-northeast-1.amazonaws.com/hackybara-polymart-api:latest
    #build: .
    container_name: polymart-api
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
